configs:
  params:
    server.insecure: true
  cmp:
    create: true
    plugins:
      tanka:
        generate:
          command: ["/usr/local/bin/tk"]
          args: ["show",".","--dangerous-allow-redirect"]
        discover:
          fileName: "jsonnetfile.json"
          # Adjusting the discovery to focus on the structured use of environments and libraries
          find:
            glob: "environments/**/*.jsonnet"
            command: ["/bin/sh", "-c", "find ./environments -type f -name '*.jsonnet'"]

repoServer:
  extraContainers:
    - name: tanka-plugin
      command: ["/var/run/argocd/argocd-cmp-server"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      image: grafana/tanka:main-1975c28
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: tanka.yaml
          name: argocd-cmp-cm
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm

# repositories:
#   main-repo:
#     url: https://github.com/gosro/p2p-devops-test.git
#   traefik:
#     url: https://traefik.github.io/charts
#     type: helm

# server:
#   ingress:
#     enabled: true
#     hostname: argocd.p2p-test.local
#     annotations:
#       traefik.ingress.kubernetes.io/router.tls: "true"