apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gosro/p2p-devops-test.git'
    path: 'my-k8s-dev/environments/default'
    targetRevision: HEAD
    plugin:
      name: tanka
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
